disabled_theme: jekyll-theme-Slate
disabled_remote_theme: Hyde
remote_theme: Hamilton
skin: Daylight
title: Epoxy / Resin & Wood Notes
author: Daniel Wittenberg
email: dwittenberg2008@gmail.com
date: 2024-12-18 11:28:00 -0000